VikeLabs/courseup

- functions/build/routes.ts
- functions/build/swagger.json
- functions/package-lock.json
- functions/package.json
- functions/src/courses/Course.controller.ts
- functions/src/courses/Course.service.ts
- functions/src/sections/Section.service.ts
- src/app/content/Content.tsx
- src/fetchers.tsx
Notable changes: need to update to specify term for retrieving data.
> Update to use v1.0.0-alpha of uvic-course-scraper

- package-lock.json
- src/app/header/components/TermButtons.tsx
#42 
Using the same logic as when a button is clicked, the current term is now set as the active button on initial load.
> Fix correct term not being displayed on initial load

- .github/CODEOWNERS
- .github/pull_request_template.md
Small quality of life changes. Now all PRs will have a simple template to follow and PRs will automatically request review from the clockwork team.
> Create pull_request_template.md and CODEOWNERS

- .github/workflows/frontend.yaml
- package-lock.json
- package.json
- src/index.tsx
Adds [Sentry](https://sentry.io/) on the React application and also adds a "release" stage for Sentry integration. This stage adds a "release" but also uploads the source maps. This allows the source maps to be relevant to the error for a given release.
> Setup Sentry

- src/App.tsx
- src/app/content/Content.tsx
- src/app/sidebar/Sidebar.tsx
- src/app/sidebar/containers/SidebarContainer.tsx
Closes #51 Use the subject and code to make requests to /subject and /seats 
1. Create hooks for currently selected code, subject by using state
2. pass the function to sidebar.tsx
3. get selected code and subject values in sidebar component
4. use these values to the content component to rendering /section and /seat faster.
> save selected code, subject in App.tsx to enhence content component

- .firebaserc
- package-lock.json
- package.json
- public/index.html
- src/index.tsx
Closes #6 
- Setups up Firebase SDK on the React application currently defaulting to use the `staging` profile.
- Setups up Google Analytics with the Firebase SDK Analytics module.
- Renames the `package.json` name portion to CourseUp
- Renames the React Helmet and `index.html` title to CourseUp.
> Firebase and Analytics Setup and Namings

- src/app/header/Header.tsx
- src/app/header/components/NavButtons.tsx
- src/app/header/components/SearchBar.tsx
- src/app/header/components/TermButtons.tsx
- src/app/landing/index.tsx
Closes #XX
Rebrands the app to CourseUp and changes the color scheme a bit to match the landing image. Adds a :wave: emoji too :+1:
> Rebrand to CourseUp with minor visual tweaks

- functions/build/routes.ts
- functions/package-lock.json
- functions/package.json
> chore: update to tsoa-3.7.0

- .github/workflows/backend.yaml
> Fix Cloud Function Deployment with Default Project

- src/app/header/Header.tsx
Adds a banner alerting the user this is beta software.
> feat: add beta warning banner

- src/app/scheduler/components/SchedulerCalendar.tsx
> Scheduler - Calendar breaks styling when the current date is Monday

- .github/workflows/production.yaml
- README.md
- package.json
- src/index.tsx
Closes #133 
- Adds deployment to production via. a `workflow_dispatch` event, which is just a manual way of invoking GitHub Actions.
- Deploys to production are locked to protected branches and require a review in addition to be able to proceed with a deployment. 
- Adds handling the Firebase config between staging and production. 
- To build the React app using production using **production** configs (not to be mistaken with production `NODE_ENV`), use `REACT_APP_ENV=production`, which makes the React app build using the environment variables. 
- This also means that any preview builds are tied to the **staging** configuration rather than the production environment.
- Adds a top-level `ErrorBoundary` from Sentry to _hopefully_ propagate errors to Sentry. Make sure you disable any …
> Production Deployment

- .github/workflows/production.yaml
- src/index.tsx
Fixes the issue where the production build doesn't have environment variables for the initialization of Firebase properly defined.
> Fix: Production build environment variables 

- src/app/content/Content.tsx
- src/app/content/components/Course.tsx
- src/app/content/components/Section.tsx
Closes #XX
- Changes the button "Bookmark" to "Add to Timetable" and "Remove from Timetable" as bookmarking can be confusing on whether it's a browser bookmark. Could simplify the wording but for now it's much more clear to the user.
- Adds skeleton loading to the course content title / description and links. Before it allowed `undefined` links which would be broken. 
- Disables the add/delete button while data is loading. 
- Moves the CRN to the left given it's not very important.
- Course detail badges are smaller now.  
- Adds toast messages when course is added/deleted via the button on the course details view.
- When getting course details errors out, shows the error message (shown below)
> Add content page current state context

- src/app/scheduler/components/SchedulerSections.tsx
Closes #114 
add section table as scheduler component
Please let me know if I need to fix or modify it :)
> add section table(radio) for scheduler

- .github/workflows/populate-courses.yaml
- functions/package-lock.json
- functions/package.json
- functions/scripts/populate-courses.ts
- functions/src/courses/Course.service.ts
This PR is a _test run_ of invoking scripts that interact with Firestore through GitHub Actions.
The goal of this PR is to allow scripts to executed on GitHub Actions and avoid having to give service account keys to everyone as well as maintain a log of invocations and what not.
> feat: Populate course data into Firestore using script invoked through GitHub Actions

- src/app/scheduler/components/SchedulerCalendar.tsx
> fix calendar going to wrong date

- src/app/scheduler/components/SchedulerSections.tsx
> gave minW and W to box components

- src/app/header/components/SearchBar.tsx
Closes #184 
I added a label to the search form, I also added correct `chakra-ui/react` components.
New: 
Old:
NOTE: Although my screenshots make it look quite different, the only difference between the two is the positioning of the placeholder text in the new screenshots. The placeholder text in the new is a little more inwards than the old.
Please do more QA, but I am pretty sure it does not change the search function. I've tested it on my end, but I do not know all cases.
> accessibility: Add label to search form

- src/app/scheduler/components/SchedulerCalendar.tsx
> Add ghost events

- .github/workflows/deployment.yml
Fixes the artifact names in the deployment script as they were mismatched. Also makes the build step names more descriptive.
> fix: artifacts names and step names

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
Update language for pull request template and bug issue reporting. 
Please add additional language to pull request template for backend specific work.
> Documentation: Update Pull Request Template and Bug Issue Template

- src/common/feedback/index.tsx
- src/common/sidebar/containers/SidebarTemplate.tsx
- src/index.tsx
- src/pages/home/index.tsx
- src/pages/registration/containers/RegistrationContainer.tsx
The Feedback Button is now persistent as it remains on the main index page for the application. Fixed some accessibility issues (colour + image alt attribute). Updated language for feedback prompt.
Let me know if you find anything breaking, or would like to see something updated/fixed.
> Fix: Feedback Button Present on Each Page and Persistent

- package-lock.json
- package.json
- src/lib/utils/jest/index.ts
- src/pages/calendar/components/Course.tsx
- src/pages/calendar/components/__tests__/Course.test.tsx
- src/setupTests.ts
Initialized jest to allow for more in depth testing, prepare to write some tests 😉
> feat: initialize frontend testing

- src/common/header/components/GitHubButton.tsx
- src/common/header/containers/HeaderContainer.tsx
Adding a GitHub button to the navigation bar that takes user to CourseUp's GitHub repository.
I took into account the feedback left on #195 
Closes #163
> Adding GitHub button

- functions/src/index.ts
> feat: Bump rate limiting 

- functions/README.md
This README is a bit out of date, referencing NPM scripts we don't have etc. Just cleaning it up so new members don't get confused.
LMK if any descriptions are off or there's a step missing. I was having trouble reproducing on my machines 😬
> fix(docs): backend readme to be up to date

- src/common/header/components/Banner.tsx
The banner is out of date with the new header, plus we could potentially benefit from additional exposure to `Download`.
Closes #XX
> chore: Update banner

- src/common/header/components/TermSelect.tsx
- src/common/header/components/__tests__/TermSelect.test.tsx
Adds support for the new Summer 2022 semester in our header
> chore(terms): Update for Summer 2022 semester

- src/pages/contest/Contest.tsx
> fix: Contest page padding on mobile devices

- .eslintrc
- .gitignore
- README.md
- jest.config.js
- next-env.d.ts
- package-lock.json
- package.json
- pages/_app.tsx
- pages/api/hello.ts
- pages/index.tsx
- src/common/header/components/__tests__/Banner.test.tsx
- src/common/header/components/__tests__/NavButtons.test.tsx
- src/common/header/components/__tests__/TermSelect.test.tsx
- src/common/layouts/__tests__/Page.test.tsx
- src/pages/booklist/components/BooklistHeading.tsx
- src/pages/calendar/components/Hours.tsx
- src/pages/import/index.tsx
- src/pages/scheduler/components/share/SelectedCoursesCardList.tsx
- tsconfig.json
This PR bootstraps Next.js within the repository. It actually doesn't get used and all the commands that work for Next.js are documented in the README.
This PR also updates some core dependencies which have minor API changes of which have been properly addressed. The PR should not change the behaviour of the application and any such changes are errors/bugs introduced in this PR.
Subsequent work will start using Next.js and configure the deployment for it etc.
> feat: Next.js bootstrapping

- src/pages/registration/components/RegistrationHeading.tsx
Updating registration steps as per #343 
Also adding a disclaimer about checking prerequisites before registering
Closes #343
> Updating registration steps and adding warning about prereqs

- src/pages/calendar/containers/Content.tsx
Proposed Fix: The course title and subtitle are now permanently on two lines. The button in centered as previously, and is start when in smaller screens. As well, the button is icon only at smaller screens.
Took inspiration from https://github.com/VikeLabs/courseup/pull/320
Closes #345 
---
Let me know if these changes need refinement based on your design vision. The breakpoints and font size can be modified.
> fix: Course Title and Subtitle Visual Bug w/ Add/Delete Button on Course Page

- .github/workflows/populate-courses.yaml
- .github/workflows/populate-textbooks.yaml
Pins the Google Cloud SDK action version used in workflows.
Closes #XX
> fix: pin gcloud sdk action version

- src/common/header/components/Banner.tsx
- src/common/header/components/TermSelect.tsx
- src/common/header/components/__tests__/Banner.test.tsx
- src/common/header/components/__tests__/TermSelect.test.tsx
- src/common/header/containers/__tests__/HeaderContainer.test.tsx
Changes the frontend to support the new calendar for winter 22/23. Changed the banner to advertise that we support it cause why not.
> Update terms to support Winter 2022-23

- functions/build/routes.ts
- functions/src/sections/Section.service.ts
Changes the sections endpoint to return `buildingAbbreviation` instead of `buildingAccronym` as abbreviation is a more accurate representation of the data and this matches what we have in the frontend.
I think `routes.ts` changes are all style based 🤷
> fix: Change buildingAccronym to buildingAbbreviation

- functions/build/routes.ts
- functions/build/swagger.json
- functions/package-lock.json
- functions/package.json
- functions/scripts/populate-textbooks.ts
- functions/src/db/collections.ts
- src/lib/fetchers.tsx
This PR updates the textbook population script to query Amazon to generate valid Amazon Canada URLs.
It first converts the ISBN from to ISBN10 which is the format the Amazon URL works with.
It then tests the constructed URL. If it is invalid a 404 is returned and the URL is not stored in the database. If it is valid it stores it in the database. In both cases, the ISBN10 format is stored as well.
This PR relates to https://github.com/VikeLabs/courseup/pull/367 which updates the textbooks page.
> feat: add default Amazon urls based on textbook ISBN

- .github/workflows/security.yml
This PR implements the CodeQL security scan built by GitHub. As described by [GH](https://github.com/github/codeql-action): "this action runs GitHub's industry-leading semantic code analysis engine, CodeQL, against a repository's source code to find security vulnerabilities".
This action runs on PR's against `main`, on `main` itself, and on a schedule every Sunday morning @ 7:00 UTC
Ran the security scan in my fork repo and don't see any security advisory's, looks a-ok!
> feat: Add CodeQL CI security scan

- .github/workflows/frontend.yaml
- src/index.tsx
Given Firebase previews are broken, this PR allows Vercel to be used for previews.
> feat: Use Vercel for previews

- src/pages/calendar/components/Section.tsx
Just adding additional key for recognizing badges based on comments on courses
Closes #XX
Just a small change, not sure what the best way to add small changes like this
> Adding additional course badges

- functions/src/server.ts
Removes the Redis rate-limit due to migrating to Next.js and removing the Redis subscription.
Closes #XX
> feat: remove rate limit for migration to nextjs

- src/common/header/containers/HeaderContainer.tsx
- src/common/header/containers/__tests__/HeaderContainer.test.tsx
Adds some extra warnings to the CourseUp banner regarding UVic's outage tomorrow and the general bugs we've been facing lately until we get the endpoints figured out.
Should this be phrased differently? Not really sure if CourseUp has had messages like these in the past?
> Outage & Bug Warning

- src/pages/home/containers/Landing.tsx
> Make some cool changes

- src/pages/home/containers/Landing.tsx
> Revert "Make some cool changes"

- src/common/header/containers/HeaderContainer.tsx
- src/common/header/containers/__tests__/HeaderContainer.test.tsx
Updated the banner to announce the summer 2023 calendar is available. I got rid of the technical difficulties tip too, cause things seem to be pretty smooth.
> Update banner for summer 2023 announcement

- src/pages/calendar/containers/Section.tsx
- src/pages/registration/containers/CourseContainer.tsx
Avoids an infinite rendering loop causing crashes or freezing on the registration page
Modify seats to use memory as previously it would update infinitely causing issues
Closes #455
> Use memory for seat data

- src/pages/calendar/components/Section.tsx
Removed a duplicate CSC badge that was pushed for some courses
Closes #411
> Removing duplicate course tag

- functions/package-lock.json
- functions/package.json
> bump scraper version

- src/common/layouts/sidebar/containers/Sidebar.tsx
- src/lib/hooks/useTerm.ts
- src/pages/booklist/containers/BooklistContainer.tsx
- src/pages/registration/containers/RegistrationContainer.tsx
- src/pages/scheduler/components/SchedulerSections.tsx
The registration and booklist pages were broken, completely crashing the browser. It appears to have something to do with the `useTerm` hook @logankuzyk added. It's a nice hook to have, so ideally whatever was breaking is fixed, but returning back to the original implementation is a good hotfix. I also made some minor UI changes to the  course cards on the scheduler sidebar, feel free to veto.
Closes #XX
> Fix registration and booklist page bugs, cleanup some UI

- src/common/header/containers/HeaderContainer.tsx
Added info for kick-off to top banner with link to vikelabs.ca. Would it be good to also change banner color on kick off info to something like red??
> Adds info for kick off to top banner

- src/common/header/components/TermSelect.tsx
- src/common/header/containers/HeaderContainer.tsx
> Remove Kickoff Banner
