VikeLabs/courseup

.storybook/main.js
.storybook/preview.js
README.md
package.json
src/app/content/Content.stories.tsx
src/app/content/Content.tsx
src/app/header/Header.stories.tsx
src/app/header/Header.tsx
src/app/sidebar/Sidebar.stories.tsx
src/app/sidebar/Sidebar.tsx

Added Storybook.
Stories for content, header, and sidebar.
Updated README with npm downgrade note because of this issue: https://github.com/storybookjs/storybook/issues/12983
Added Storybook design addon:

Storybook setup

---

functions/build/routes.ts
functions/build/swagger.json
functions/src/subjects/Subject.controller.ts
functions/src/subjects/Subject.model.ts
functions/src/subjects/Subject.service.ts

Adds `/subjects/{term}` to get a list of subjects with their respective title and shortform.

Add endpoints to retrieve list of subjects

---

functions/src/courses/Course.controller.ts

See if stale-while-revalidate helps the responsiveness of the API. This PR merely adds the cache headers for such.

feat: testing stale-while-revalidate and stale-while-error

---

src/app/header/components/TermButtons.tsx

Fixed a bug where the maximum depth was being exceeded from the `useEffect` call in `TermButtons.tsx`. The variable `terms` was being called within the method which caused an infinite loop.

Fix maximum depth bug

---

functions/build/routes.ts
functions/build/swagger.json
functions/src/courses/Course.controller.ts
functions/src/courses/Course.model.ts
functions/src/courses/Course.service.ts
functions/src/db/collections.ts
functions/src/sections/Section.model.ts
functions/src/sections/Section.service.ts
functions/src/server.ts

This PR changes the usage of Firestore significantly in order to allow more features in regards to data queries. 
The goal of this PR is to allow courses to be filtered based on whether they are in session for a given term. This allows the application to only show courses that are in session. 
The previous way we were storing course metadata (`course_mappings`, which stored the CRNs for a given course and term ie. `202101SENG265`) 
This did not allow query based on an attribute since the `term` was not stored. The only way to query would be to get all the keys and do some string manipulation on the key itself. That seemed janky so this restructures how data is stored in Firebase.
The key is still constructed the same way where the `term`, `subject`, `code` and `crns` are also stored, …

feat: Add filtering of courses based on availibility 

---

.github/workflows/frontend.yaml

Enables temporary frontend build and hosting when a PR is made. The build/hosting lasts 1 week.

Enable Firebase Preview Builds

---

src/app/content/Content.tsx
src/app/content/components/Section.tsx

Closes #106 
Added links to the UVic undergrad calendar and class schedule listings at bottom of content component. The links send the user in a new tab to the courses respective pages for the Kuali and BAN1P data. I've purposely left off the section details link because there would have to be a link for each section and that can be accessed from the listings link.

Add links to UVic pages at bottom of content

---

src/app/mobile/index.tsx
src/index.tsx
src/routes.tsx

Jumped on the opportunity to add a warning for anyone trying to access the site on mobile. Modal pops up when the screen gets < 600px wide. It can be closed by the user, but this can be easily changed if we want to fully block the user from using the page.

Add mobile view warning

---

.github/workflows/backend.yaml
.github/workflows/frontend.yaml
.github/workflows/production.yaml

Closes #XX
Stops the backend CI running if only frontend files change. Also adds a test "Promote to Production" action (which doesn't actually do that).

fix: stop having backend CI run if only frontend files change

---

functions/src/courses/Course.service.ts

Closes #175 
This PR fixes an issue where the population script (which uploads in batches of less than 450) didn't flush the courses still not yet uploaded by forgetting to flush these courses towards to the end of the array.
The example given, STAT350 and STAT254 are towards the end which is why they were never populated.
The fix is simply adding a `commit()` at the end.

fix: When batch uploading to Firestore, commit the courses remaining

---

.github/workflows/frontend.yaml

Stops having the preview builds trying to execute when they can't due to not having access to repository secrets.

fix: stop having forked repos try jobs that need repo secrets

---

src/app/landing/index.tsx

Closes #156 
* Add responsive design to the landing page content.
The `VIKE LABS` part of the landing page is still open for changes. Feel free to give a better alternative or modifications.
NOTE: This does not fix the height + content issue, and only fixes the responsiveness. 
Known Issue:
This will not be fixed in this PR as it is more relevant to course scheduling page than landing page. This will need to be fixed once a suitable responsive design is created for this page.

fix: Responsive Landing Page

---

src/app/header/components/TermButtons.tsx
src/app/registration/components/RegistrationHeading.tsx
src/app/registration/components/RegistrationMinimized.tsx
src/app/registration/components/RegistrationSection.tsx
src/app/registration/containers/CourseContainer.tsx
src/app/registration/containers/RegistrationContainer.tsx
src/app/registration/index.tsx
src/app/scheduler/components/SchedulerSidebar.tsx
src/pages/registration/index.tsx
src/routes.tsx

Closes #162 
Adds a registration page users can access via the timetable which provides a link to UVic's registration page & easy-to-copy CRNs for each of their saved sections. The idea is users can quickly copy and paste CRNs into UVic's registration page to easily register based on their timetable made on the website.
**looking for any a11y recommendations**

Registration view

---

src/app/scheduler/components/SchedulerSidebar.tsx

Closes #204 
Added some padding to the bottom of the scheduler sidebar to give room for the feedback button. This allows there to be space for the feedback button to occupy that doesn't cover a remove or info button of a saved course.

Fix feedback button blocking course cards

---

src/pages/registration/components/RegistrationHeading.tsx
src/pages/registration/components/RegistrationSection.tsx
src/pages/registration/containers/CourseContainer.tsx
src/pages/registration/containers/RegistrationContainer.tsx

Closes #222 
Adding additional responsiveness to an already responsive component (registration page). Updated instructions to be accessible and mobile friendly.
Note: https://github.com/VikeLabs/courseup/issues/227 has been created, as it requires a more higher level change.
Desktop: 
Mobile:
Desktop:
Mobile:

fix: Responsiveness - Registration Page

---

.github/workflows/frontend.yaml

Adds a SHA as a static file to the application. This let's developers check which version of the application they are hitting.

feat: add git sha as static asset for frontend

---

src/pages/scheduler/components/SchedulerSidebar.tsx

#193 added the option to collapse courses on the timetable sidebar, however the edge case where users who had timetables made prior to this additional attribute being added was not addressed. Currently on staging if you already had courses added, they will default to be minimized since `showSections` is undefined, which isn't the end of the world but I'd rather we avoid this.

fix: sections being hidden for courses added before this feature

---

package-lock.json
package.json
src/pages/scheduler/components/SchedulerCalendar.tsx

Fixes the date-fns imports to use the ESM variant so the bundler can properly tree shake. This fix resulted in significant savings in bundle size! 
Also adds a `npm run analyze` which will analyze the bundle after it has been built.
Note, one of dependencies of a dependency is using a non-tree shakable version of lodash...

fix: Use ECMAScript Imports for date-fns so they can be tree shakable

---

src/common/sidebar/containers/SidebarContainer.tsx

Changed background colour of search results header to match dark mode
Closes #269

Fixed "Search Results" being wrong color in dark mode

---

src/common/sidebar/components/SearchResults.tsx

Fixes a bug that causes a click event on the info button on timeline search results to have a conflict with another click event. The click event on the button redirects the page to the course information page as intended.
Closes #215
This bug and fix only applies to the course cards that appear in the search results of the Timeline page.
Clicking the blue info icon as shown in this image...
...briefly shows the correct link address but is quickly replaced by an incorrect link address that also blocks the page from redirecting incorrectly.
...now is no longer blocked and redirects to the correct link address.

Bug Fix for issue #215 info button

---

src/pages/scheduler/components/SchedulerCalendar.tsx

Fixes the events cache key not being unique for classes with multiple time slots for a given section.
This fix is implemented by building the cache key with the meeting days and time appended to the existing one.
Closes #296

fix: make calendar events cache key more unique

---

src/lib/utils/__tests__/terms.test.ts
src/lib/utils/terms.ts

By UVic definition, the semester from January-April is technically called the "Spring" semester, which we have been calling "Winter". Changed that in this PR.
Closes #XX

fix(terms): Change winter term to spring

---

.github/workflows/populate-textbooks.yaml
functions/scripts/populate-textbooks.ts

A simple PR to allow the term to be passed in as an argument rather than be hardcoded to a specific term. The GitHub action will now have a term input option.
The button itself will need to be enabled after we can verify the data is loaded in properly. This can be bypassed by just going directly to the page.

feat: allow loading in other terms for textbooks

---

README.md
src/pages/booklist/components/BooklistHeading.tsx

Fixes that the term is hardcoded and the WIP branding is left in the README file.

fix: booklist term and README logo

---

src/lib/hooks/useSavedCourses.ts
src/pages/booklist/components/Textbook.tsx
src/pages/booklist/containers/BooklistContainer.tsx
src/pages/scheduler/components/Toolbar.tsx

This PR adds event tracking using Google Analytics for the following events
- When a user views the textbooks page.
- When a user clicks on a textbook url, the url is the event payload
- When a user loads their saved courses the subject of each course is as the payload
- When a user adds a course to their saved courses, the subject of that course is the payload.
- When a user downloads their schedule.
Any events without a payload are simply an event without any additional metadata (ie. it happened)
The primary motivation of tracking these events is to gain an understanding which features are being used and what the overall picture is in regards to the subjects of courses. This will allow a loose understanding of faculty adoption of the application.
This data will be used to bolster …

feat: textbook and calendar download tracking

---

.eslintrc
package-lock.json
package.json
src/common/sidebar/containers/SidebarContainer.tsx

Given we are enforcing it via PRs but not actually with eslint, this adds camelCase as a rule which is considered an error if it fails.
https://eslint.org/docs/2.0.0/rules/camelcase

chore: add camelCase eslint rule as an error

---

src/pages/import/components/ImportCalendar.tsx
src/pages/import/index.tsx
src/pages/scheduler/components/CourseCard.tsx
src/pages/scheduler/components/SchedulerCalendar.tsx
src/pages/scheduler/components/Toolbar.tsx
src/pages/scheduler/components/share/ShareButton.tsx
src/pages/scheduler/containers/SchedulerContainer.tsx
src/pages/scheduler/styles/calendar.tsx

Fixes a visual bug where the times aren't visible on mobile calendars in light mode. Weirdest bug ever. Also made the toolbar responsive, so the calendar is usable in a read only mode. Enabled the calendar to be viewable from timetable sharing!

feat: Mobile calendar visual fixes

---

src/pages/scheduler/components/CourseCard.tsx
src/pages/scheduler/components/SchedulerSidebar.tsx

The showSections toggle appears on courses that do not have any sections. This can be confusing to people and make them think there is a bug. This PR proposes to hide the showSections toggle when no sections are available. 
I choose to hide instead of preventing user interaction to remove clutter.
Closes #347
I'm not sure if this is how you want to handle the toggle, let me know if you have another idea and the general approach that I should take.

fix: Hide and Show showSections Toggle

---

src/pages/scheduler/components/SchedulerSections.tsx

This change displays the "Additional Info" text, also shown on the Calendar page, on the Timetable page as well. This info is displayed as a Chakra UI Tooltip, and is shown whenever you hover over the resulting section. When no "Additional Info" is present, no tooltip is shown.
As far as code goes, this change was trivial. `section.additionalNotes` was already present in the scope where `Option` was called, so I simply added it as a parameter. Inside of `Option`, I simply wrapped the entire contents in a tooltip.
Closes #354
Nothing happens on hover
https://user-images.githubusercontent.com/56709101/158445656-f78ddc9e-b06b-4c11-b5dd-b10a62305758.mp4

Show "Additional Notes" in Timetable view using Tooltip

---

src/pages/calendar/containers/Section.tsx
src/pages/registration/containers/CourseContainer.tsx

Switches the frontend to make calls to banner v9 instead of v8. 
Don't need to merge this yet, but if uvic goes through and deprecates v8 like they said we need this.

Switch frontend to use banner v9

---

.env
functions/build/routes.ts
functions/src/sections/Section.controller.ts
src/pages/calendar/components/Section.tsx

Fixes the V9 endpoint to return `TBA` for `meetingTime.where` instead of `null null` to match the V8 data. This happens for online courses typically.

fix: `meetingTime.where` to be `TBA`

---

src/pages/scheduler/components/share/ShareTimetableModal.tsx

Fixes the timetable share modal size based on screen size by swapping the values.
Closes #XX

fix: Timetable share modal size

---

jest.config.js
package-lock.json
package.json
src/common/layouts/Page.tsx
src/common/layouts/styles/swiperPagination.tsx
src/lib/theme.tsx
src/lib/utils/jest/__mocks__/moduleMock.js
src/pages/scheduler/containers/SchedulerContainer.tsx
src/pages/scheduler/index.tsx

This PR changes the Page component to be responsive on mobile using Swiper. A menu bar at the bottom shows your current page and you can swipe or click to switch between them.
Closes #318 
Here's a little GIF of it in action: https://imgur.com/a/wj0E4x6
When a user starts typing something in the menubar, it slides them back to the left most slide (left sidebar, as it includes search results).
This is done using a bit of a workaround using `useState`. The best would be to use the `useSwiper` hook they provide, but that needs to be in a _direct_ child component of `Swiper`, which is not possible for our use case since the menu bar is the one that triggers the slide, which won't be inside Swiper...

Feat: Responsive timetable

---

src/common/header/containers/HeaderContainer.tsx

Remove outage warning since it's past. I'll leave the technical difficulty one for now since some of the endpoints are still down.

remove outage warning

---

src/pages/calendar/components/Seats.tsx
src/pages/calendar/containers/Section.tsx

When the /seats endpoint fails, it removes all other info about a course even if it exists. This PR moves the error message into the component so that the rest still loads for the user.

Specify seat error

---

src/lib/hooks/useTerm.ts

There was a re-render loop happening when the term was included in the URL parameter. Aomi pointed out that the issue was caused by the fact that the hook would use its own `setTerm` function to update the term when the URL parameter was there. I updated the logic so it now would use the URL parameter as the 'first priority' default value instead of setting it after the fact.

Fix re-render loop caused by `useTerm`

---

src/lib/api/getSections.ts
src/pages/scheduler/components/SchedulerSections.tsx

This change displays seat info on the timetable page. I found this to be a usability improvement when creating a schedule after the registration date, as most sections had filled up but I had to tab back and forth to the Courses tab to see which ones were full.
The timetable view on a full-sized 1080p monitor (new vs old):
The timetable view on a scaled 1080p laptop display (new vs old):
I'm not too happy with how the change squishes the rest of the columns on smaller devices. I'm open to suggestions on how to improve that, my current strategy was just to make every existing column smaller.

display seat info on timetable sidebar

---

src/common/header/containers/HeaderContainer.tsx
src/lib/hooks/useTerm.ts

Changes "Winter 2023 calendar is now available", with link leading to Fall 2023 to "The Fall 2023 and Spring 2024 calendars are now available", with links to each individual winter term
This also fixes an issue that clicking on banner items (i.e. changing the URL term param) doesn't actually update the selected term.
Closes #475

Change banner to be clearer about winter terms

---

src/common/layouts/sidebar/components/CoursesList.tsx
src/pages/calendar/components/Seats.tsx
src/pages/scheduler/components/SchedulerSections.tsx

This PR highlights the current course looking at the user's URL and it also fixes a bug that shows full waitlists for 0/0, so this hides the waitlist for those that have no total capacity for both the course sections and the scheduler sidebar.
Closes #484

Highlight selected course & Hide waitlist when there isn't one

---

src/common/header/components/TermSelect.tsx
src/common/header/containers/HeaderContainer.tsx

Moves the term selector closer to the search bar for better UX. Also conditionally applies colors to selector border based on term. 
Closes #372

Moves term selector

---

src/pages/scheduler/components/SchedulerSections.tsx

Fixes the conditional for the section and waitlist being full or not; if there are more people enrolled than there are spots, then the section is full and should be indicated by colouring the badge red
Closes #500

Fix sectionFull conditionals

---

src/common/header/components/TermSelect.tsx
src/common/header/containers/HeaderContainer.tsx

Remove kickoff banner

---

src/pages/calendar/containers/Section.tsx
src/pages/registration/containers/CourseContainer.tsx

Disable v9 flag to stop using banner data and use scraper instead. Tested locally and seemed to work properly with the data already in prod db
Closes #510

Stop using v9 data (banner)
